services:
  upload-service:
    container_name: upload-service
    image: hoonseung/upload-service:latest

    depends_on:
      - postgres

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - DB_SERVER_URL=${DB_SERVER_URL}
      - FE_SERVER_HOST=${FE_SERVER_HOST}
      - FE_SERVER_PORT=${FE_SERVER_PORT}

    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}

    networks:
      - upload_network

  upload-view:
    container_name: upload-view
    image: hoonseung/upload-view:latest

    depends_on:
      - postgres
      - upload-service

    environment:
      - VITE_SERVER_API_URL=${BE_SERVER_URL}

    ports:
      - ${FE_SERVER_PORT}:80

    networks:
      - upload_network


  postgres:
    container_name: order-postgres
    image: postgres:14.4
    ports:
      - "25432:5432"

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    restart: on-failure

    volumes:
      - order_postgres_data:/var/lib/postgresql/data

    networks:
      - upload_network

volumes:
  order_postgres_data:

networks:
  upload_network:
    name: upload_network
    driver: bridge


